import { Account, Transaction, UserProfile } from '@/types';
import { toSmallestUnit } from './money';

export const INITIAL_USER_PROFILE: UserProfile = {
  id: 'user_nexa_demo',
  name: 'Alex Rivera',
  email: 'alex.rivera@trivon.io',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  homeCurrency: 'USD',
  trackedCurrencies: ['USD', 'EUR', 'GBP', 'NGN', 'BTC', 'ETH'],
  monthlyBudgetSmallestUnit: toSmallestUnit(6500, 'USD'),
  isDemo: true,
};

export const INITIAL_ACCOUNTS: Account[] = [
  {
    id: 'acc_chase_main',
    name: 'Chase Premier Checking',
    institution: 'Chase Bank',
    institutionColor: '#117ACA',
    currency: 'USD',
    balanceSmallestUnit: toSmallestUnit(24850.40, 'USD'),
    type: 'bank',
    accountNumberMasked: '•••• 4821',
    connectedAt: '2026-01-15T10:00:00Z',
    isDemo: true,
    historySparkline: [21000, 22400, 21800, 23900, 24850],
    updatedAt: 'Just now',
  },
  {
    id: 'acc_wise_eur',
    name: 'Wise Multi-Currency (EU)',
    institution: 'Wise',
    institutionColor: '#9FE870',
    currency: 'EUR',
    balanceSmallestUnit: toSmallestUnit(18420.00, 'EUR'),
    type: 'fintech',
    accountNumberMasked: '•••• BE89',
    connectedAt: '2026-02-01T08:30:00Z',
    isDemo: true,
    historySparkline: [12000, 14500, 16200, 15800, 18420],
    updatedAt: '2m ago',
  },
  {
    id: 'acc_revolut_gbp',
    name: 'Revolut Business Pro',
    institution: 'Revolut',
    institutionColor: '#0075EB',
    currency: 'GBP',
    balanceSmallestUnit: toSmallestUnit(9650.75, 'GBP'),
    type: 'fintech',
    accountNumberMasked: '•••• 9102',
    connectedAt: '2026-02-10T14:15:00Z',
    isDemo: true,
    historySparkline: [8200, 8900, 9400, 9100, 9650],
    updatedAt: '5m ago',
  },
  {
    id: 'acc_binance_crypto',
    name: 'Binance Cold Vault',
    institution: 'Binance',
    institutionColor: '#F0B90B',
    currency: 'BTC',
    balanceSmallestUnit: toSmallestUnit(0.64500000, 'BTC'),
    type: 'crypto',
    accountNumberMasked: 'bc1q•••79x',
    connectedAt: '2026-01-20T19:00:00Z',
    isDemo: true,
    historySparkline: [0.55, 0.58, 0.62, 0.60, 0.645],
    updatedAt: '1m ago',
  },
  {
    id: 'acc_gtbank_ngn',
    name: 'GTBank Corporate',
    institution: 'Guaranty Trust Bank',
    institutionColor: '#E04A15',
    currency: 'NGN',
    balanceSmallestUnit: toSmallestUnit(8450000.00, 'NGN'),
    type: 'bank',
    accountNumberMasked: '•••• 0341',
    connectedAt: '2026-02-18T11:45:00Z',
    isDemo: true,
    historySparkline: [6200000, 7100000, 7800000, 8100000, 8450000],
    updatedAt: '12m ago',
  },
  {
    id: 'acc_stripe_usd',
    name: 'Stripe SaaS Payouts',
    institution: 'Stripe',
    institutionColor: '#635BFF',
    currency: 'USD',
    balanceSmallestUnit: toSmallestUnit(12150.00, 'USD'),
    type: 'fintech',
    accountNumberMasked: 'acct_•••94f',
    connectedAt: '2026-01-10T09:00:00Z',
    isDemo: true,
    historySparkline: [9500, 10800, 11200, 11900, 12150],
    updatedAt: 'Just now',
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx_01',
    accountId: 'acc_chase_main',
    accountName: 'Chase Premier Checking',
    amountSmallestUnit: toSmallestUnit(6500.00, 'USD'),
    type: 'income',
    currency: 'USD',
    category: 'Client Payment',
    description: 'Q3 UI/UX Design Sprint Retainer',
    merchant: 'Acme Global Ventures LLC',
    date: '2026-09-01T15:30:00Z',
    createdAt: '2026-09-01T15:30:00Z',
    status: 'completed',
    isDemo: true,
  },
  {
    id: 'tx_02',
    accountId: 'acc_wise_eur',
    accountName: 'Wise Multi-Currency (EU)',
    amountSmallestUnit: toSmallestUnit(4200.00, 'EUR'),
    type: 'income',
    currency: 'EUR',
    category: 'Contract Work',
    description: 'Frontend Architecture Consultation (Next.js)',
    merchant: 'Nordic FinTech GmbH (Berlin)',
    date: '2026-08-30T11:20:00Z',
    createdAt: '2026-08-30T11:20:00Z',
    status: 'completed',
    isDemo: true,
  },
  {
    id: 'tx_03',
    accountId: 'acc_revolut_gbp',
    accountName: 'Revolut Business Pro',
    amountSmallestUnit: toSmallestUnit(2400.00, 'GBP'),
    type: 'income',
    currency: 'GBP',
    category: 'Salary & Retainer',
    description: 'Monthly Engineering Advisory Fee',
    merchant: 'Veloce Labs Ltd (London)',
    date: '2026-08-28T09:45:00Z',
    createdAt: '2026-08-28T09:45:00Z',
    status: 'completed',
    isDemo: true,
  },
  {
    id: 'tx_04',
    accountId: 'acc_gtbank_ngn',
    accountName: 'GTBank Corporate',
    amountSmallestUnit: toSmallestUnit(3500000.00, 'NGN'),
    type: 'income',
    currency: 'NGN',
    category: 'Client Payment',
    description: 'Mobile App Core Milestone 2 Delivery',
    merchant: 'PayPulse Technologies Lagos',
    date: '2026-08-27T14:10:00Z',
    createdAt: '2026-08-27T14:10:00Z',
    status: 'completed',
    isDemo: true,
  },
  {
    id: 'tx_05',
    accountId: 'acc_chase_main',
    accountName: 'Chase Premier Checking',
    amountSmallestUnit: toSmallestUnit(220.00, 'USD'),
    type: 'expense',
    currency: 'USD',
    category: 'Software & SaaS',
    description: 'Cursor Pro + Claude Enterprise AI Seats',
    merchant: 'Cursor Inc / Anthropic',
    date: '2026-08-26T18:05:00Z',
    createdAt: '2026-08-26T18:05:00Z',
    status: 'completed',
    isDemo: true,
  },
  {
    id: 'tx_06',
    accountId: 'acc_chase_main',
    accountName: 'Chase Premier Checking',
    amountSmallestUnit: toSmallestUnit(450.00, 'USD'),
    type: 'expense',
    currency: 'USD',
    category: 'Cloud & Servers',
    description: 'Vercel Enterprise & Supabase Pro Cluster',
    merchant: 'Vercel Inc.',
    date: '2026-08-25T10:15:00Z',
    createdAt: '2026-08-25T10:15:00Z',
    status: 'completed',
    isDemo: true,
  },
  {
    id: 'tx_07',
    accountId: 'acc_revolut_gbp',
    accountName: 'Revolut Business Pro',
    amountSmallestUnit: toSmallestUnit(185.50, 'GBP'),
    type: 'expense',
    currency: 'GBP',
    category: 'Food & Dining',
    description: 'Client Lunch Meeting @ Soho House London',
    merchant: 'Soho House Dean St',
    date: '2026-08-24T13:40:00Z',
    createdAt: '2026-08-24T13:40:00Z',
    status: 'completed',
    isDemo: true,
  },
  {
    id: 'tx_08',
    accountId: 'acc_wise_eur',
    accountName: 'Wise Multi-Currency (EU)',
    amountSmallestUnit: toSmallestUnit(890.00, 'EUR'),
    type: 'expense',
    currency: 'EUR',
    category: 'Travel & Transport',
    description: 'Lufthansa Flights to Tech Summit Lisbon',
    merchant: 'Lufthansa Group',
    date: '2026-08-22T08:15:00Z',
    createdAt: '2026-08-22T08:15:00Z',
    status: 'completed',
    isDemo: true,
  },
  {
    id: 'tx_09',
    accountId: 'acc_gtbank_ngn',
    accountName: 'GTBank Corporate',
    amountSmallestUnit: toSmallestUnit(450000.00, 'NGN'),
    type: 'expense',
    currency: 'NGN',
    category: 'Rent & Living',
    description: 'Lekki Co-working Studio Dedicated Desk & Power',
    merchant: 'Leadspace Yaba / Lekki',
    date: '2026-08-20T16:00:00Z',
    createdAt: '2026-08-20T16:00:00Z',
    status: 'completed',
    isDemo: true,
  },
  {
    id: 'tx_10',
    accountId: 'acc_binance_crypto',
    accountName: 'Binance Cold Vault',
    amountSmallestUnit: toSmallestUnit(0.04500000, 'BTC'),
    type: 'income',
    currency: 'BTC',
    category: 'Crypto Trading',
    description: 'Staking Yield & Liquidity Protocol Reward',
    merchant: 'Babylon Staking Protocol',
    date: '2026-08-18T03:30:00Z',
    createdAt: '2026-08-18T03:30:00Z',
    status: 'completed',
    isDemo: true,
  },
  {
    id: 'tx_11',
    accountId: 'acc_stripe_usd',
    accountName: 'Stripe SaaS Payouts',
    amountSmallestUnit: toSmallestUnit(3890.00, 'USD'),
    type: 'income',
    currency: 'USD',
    category: 'Software & SaaS',
    description: 'Micro-SaaS Subscriptions Monthly MRR',
    merchant: 'Stripe Direct Connect',
    date: '2026-08-15T00:00:00Z',
    createdAt: '2026-08-15T00:00:00Z',
    status: 'completed',
    isDemo: true,
  },
  {
    id: 'tx_12',
    accountId: 'acc_chase_main',
    accountName: 'Chase Premier Checking',
    amountSmallestUnit: toSmallestUnit(1299.00, 'USD'),
    type: 'expense',
    currency: 'USD',
    category: 'Hardware & Gear',
    description: 'Apple Studio Display 5K for Workstation',
    merchant: 'Apple Store 5th Ave',
    date: '2026-08-12T14:50:00Z',
    createdAt: '2026-08-12T14:50:00Z',
    status: 'completed',
    isDemo: true,
  },
];

export const INSTITUTIONS_LIST = [
  { name: 'Chase Bank', type: 'bank' as const, currency: 'USD' as const, color: '#117ACA', logo: '🏛️' },
  { name: 'Bank of America', type: 'bank' as const, currency: 'USD' as const, color: '#E31837', logo: '🏦' },
  { name: 'Wise (TransferWise)', type: 'fintech' as const, currency: 'EUR' as const, color: '#9FE870', logo: '🌐' },
  { name: 'Revolut Business', type: 'fintech' as const, currency: 'GBP' as const, color: '#0075EB', logo: '⚡' },
  { name: 'Stripe Balance', type: 'fintech' as const, currency: 'USD' as const, color: '#635BFF', logo: '💳' },
  { name: 'Binance', type: 'crypto' as const, currency: 'BTC' as const, color: '#F0B90B', logo: '🟡' },
  { name: 'Coinbase Pro', type: 'crypto' as const, currency: 'ETH' as const, color: '#0052FF', logo: '🔵' },
  { name: 'Guaranty Trust Bank (GTBank)', type: 'bank' as const, currency: 'NGN' as const, color: '#E04A15', logo: '🔶' },
  { name: 'Access Bank', type: 'bank' as const, currency: 'NGN' as const, color: '#1B365D', logo: '🏢' },
  { name: 'Royal Bank of Canada (RBC)', type: 'bank' as const, currency: 'CAD' as const, color: '#0051A5', logo: '🍁' },
  { name: 'Monzo UK', type: 'fintech' as const, currency: 'GBP' as const, color: '#FF3366', logo: '📱' },
  { name: 'Physical Cash Reserve', type: 'cash' as const, currency: 'USD' as const, color: '#10B981', logo: '💵' },
];

export const AI_QUERY_PRESETS = [
  "How much did I spend on subscriptions and SaaS this month?",
  "What is my net cash flow across all currencies converted to USD?",
  "What was my biggest income source in EUR and GBP?",
  "How much runway do I have based on last 3 months average spend?",
  "What percentage of my portfolio is in Crypto vs Fiat?",
];
